### PR TITLE
print errors to stderr, handle -isystem

### PR DESCRIPTION
**Pull request by fingolfin**
Minor stuff... I am going to write a shell script as replacement for addguards2, too, but probably will keep it inside hpc-merge (i.e. on https://github.com/fingolfin/gap/)

### CODE REVIEW

**Comment by fingolfin** [comment]
See also issues #12 and #13.

Regarding -isystem support: Of course it also does not support -idirafter, -imultilib, -iquote, etc. etc. I think a better solution would be to change the way ward is invoked: First, only ward specific arguments should come. Then perhaps a separator like `--`. And then everything afterwards is passed through to the preprocessor untouched. That's seems to me the only way to achieve full compatibility...

**Comment by ChrisJefferson** [comment]
I agree with this entirely, I assumed (without investigation that was how it was already working, there are too many preprocessor options to both explicitly encoding them.

**Comment by rbehrends** [comment]
I have submitted an alternative pull request along what @fingolfin suggested (so far untested in the real world). With that, ward takes a `-cpp` option, where all following arguments are submitted to the preprocessor. The list is terminated with `--`. Will still have to test this, but it is a possible alternative approach.

**Comment by fingolfin** [comment]
The alternate PR does nothing to address the error handling changes in here. I'll make new PRs...

**Comment by fingolfin** [comment]
We merged #17 and #20 instead

**Pull request closed without merging**
